// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get credentials from WordPress (injected via PHP) or environment variables
declare global {
  interface Window {
    vloerbotConfig?: {
      supabaseUrl: string;
      supabaseKey: string;
      profileImage?: string;
      wpSiteUrl?: string;
      wpApiUrl?: string;
      botAvatar?: string;
      userAvatar?: string;
    };
  }
}

const getSupabaseConfig = () => {
  // Check for WordPress configuration first
  if (typeof window !== 'undefined' && window.vloerbotConfig) {
    return {
      url: window.vloerbotConfig.supabaseUrl,
      key: window.vloerbotConfig.supabaseKey,
    };
  }

  // Fallback to environment variables for development
  return {
    url: import.meta.env.VITE_SUPABASE_URL || '',
    key: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '',
  };
};

const config = getSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(config.url, config.key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});